name: "Copy to Another Repository"
description: "Copy selected files to another repository and create Pull Request (PR)."
author: "Sator Imaging"
branding:
  icon: copy
  color: purple

inputs:
  target-repo:
    required: false
    description: "Name of remote repository to copy file(s) from."
    default: "cisco-ospo/sample-project"
  target-path:
    required: true
    description: "File/folder path(s) to copy to the output repository."
    default: "*"
  output-repo:
    required: true
    description: "Name of the org/repo where the pull request will be filed."
    default: "cisco-ospo/outbound-review"
  output-branch:
    required: true
    description: "Base branch name to file the pull request against."
    default: "main"
  commit-message-prefix:
    required: false
    description: "Prefix for the git commit message."
    default: "[actions] "
  output-directory:
    required: false
    description: "Output directory to copy the file(s) to."
    default: "${{ github.event.repository.name }}"
  pr-branch-prefix:
    required: false
    description: "Prefix for the pull request branch name."
    default: "actions/${{ github.event.repository.name }}"
  pr-title:
    required: false
    description: "Title for the GitHub pull request."
    default: "🤖 GitHub Actions: ${{ github.event.repository.name }}"
  pr-message:
    required: false
    description: "Description for the GitHub pull request."
    default: "${{ github.workflow }} on ${{ github.server_url }}/${{ github.repository }}"
  git-name:
    required: false
    description: "Name of the committer/bot filing the pull request."
    default: "github-actions[bot]"
  git-email:
    required: false
    description: "Use your `@users.noreply.github.com` address if you want your icon shown in commit messages."
    default: "github-actions[bot]@users.noreply.github.com"
  git-token:
    required: true
    description: "Personal Access Token used to commit/create PR on output repository."

runs:
  using: "composite"
  steps:
    - run: echo '::echo::on'
      shell: bash

    # no way to retrieve added/modified files from github.event object.
    - run: cat "${{ github.event_path }}"
      shell: bash

    - run: echo "ACTION_REPO=$( echo $GITHUB_ACTION | sed 's/_/\//g' | sed 's/\///' )" >> $GITHUB_ENV
      shell: bash
    - run: echo "PR_BRANCH=${{ inputs.pr-branch-prefix }}---$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
      shell: bash
    - run: echo "PR_MESSAGE=${{ inputs.pr-message }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "TMP_SRCDIR=source" >> $GITHUB_ENV
    # - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
      shell: bash
    - run: echo "TMP_DSTDIR=dest" >> $GITHUB_ENV
    # - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
      shell: bash
    - run: echo "PR_TITLE_APPENDIX= - ${{ inputs.target-path }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "COMMIT_TITLE_APPENDIX= - ${{ inputs.target-path }}" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        persist-credentials: false
        path: "${{ env.TMP_SRCDIR }}"
        repository: "${{ inputs.target-repo }}"

    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        persist-credentials: false
        path: "${{ env.TMP_DSTDIR }}"
        repository: "${{ inputs.output-repo }}"

    - run: | 
       git config --global user.name "${{ inputs.git-name }}"
       git config --global user.email "${{ inputs.git-email }}"
       git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"
       mkdir -p "${{ inputs.output-directory }}"
      shell: bash
    
    - working-directory: "${{ env.TMP_DSTDIR }}"
      # mv -vf "../${{ env.TMP_SRCDIR }}/${{ inputs.target-path }}" "../${{ inputs.output-directory }}"
      run: |
        # git checkout -b "${{ env.PR_BRANCH }}"
        pwd
        ls -l ../
        ls -l ../source/
        ls -l ../source/*
        # ls -l  "../${{ env.TMP_SRCDIR }}/${{ inputs.target-path }}"
        # mv -f "../${{ env.TMP_SRCDIR }}/${{ inputs.target-path }}" "../${{ inputs.output-directory }}/"
        # mv -f /home/runner/work/outbound-review/outbound-review/source/* /home/runner/work/outbound-review/outbound-review/${{ inputs.output-directory }}/
        ls -l "../${{ inputs.output-directory }}/"
        # git add "${{ inputs.output-directory }}/."
        # git commit -am "${{ inputs.commit-message-prefix }}${{ github.event.repository.name }}${{ env.COMMIT_TITLE_APPENDIX }}"
        # git push origin HEAD
      shell: bash
  
    #- run: curl -X POST -H "Accept:application/vnd.github.v3+json" "https://${{ inputs.git-token }}@api.github.com/repos/${{ inputs.output-repo }}/pulls" -d "{ \"title\":\"${{ inputs.pr-title }}${{ env.PR_TITLE_APPENDIX }}\", \"body\":\"${{ env.PR_MESSAGE }}\", \"head\":\"${{ env.PR_BRANCH }}\", \"base\":\"${{ inputs.output-branch }}\" }"
    #  shell: bash
